"""Optional browser rendering for pages whose document links are generated by JavaScript.

Disabled by default (slow). Enable with `browser: enabled: true` in config.yaml and
`pip install playwright && playwright install chromium`. Without Playwright installed it quietly does nothing.
Note: the browser follows its own redirects/scripts; only the starting URL has been validated by the engine.
"""
from __future__ import annotations

from ..logger import log


class PlaywrightRenderer:
    def __init__(self, timeout: float = 30):
        self.timeout_ms = int(timeout * 1000)
        self._warned = False

    def render(self, url: str) -> str:
        """Return the rendered HTML of `url`, or '' when rendering is unavailable or fails."""
        try:
            from playwright.sync_api import sync_playwright
        except ImportError:
            if not self._warned:
                log.warning("Browser fallback enabled but Playwright is not installed; skipping")
                self._warned = True
            return ""
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch()
                try:
                    page = browser.new_page()
                    page.goto(url, timeout=self.timeout_ms, wait_until="networkidle")
                    return page.content()
                finally:
                    browser.close()
        except Exception as e:
            log.warning("Browser rendering failed for %s: %s", url, e)
            return ""
